version: 2.1

executors:
  default:
    working_directory: ~/repo
    docker:
      - image: cimg/ruby:3.1.2
caches:
  - &bundle_cache -repo
commands:
  defaults:
    steps:
      - checkout
      - restore_cache:
          keys:
            - *bundle_cache
      - run: bundle install --path vendor/bundle
      - save_cache:
          key: *bundle_cache
          paths:
            - vendor/bundle
  run_linters:
    steps:
      - run:
          name: rubocop
          command: bundle exec rubocop
      - run:
          name: fasterer
          command: bundle exec fasterer
  run_specs:
    steps:
      - run:
          name: run specs
          command: |
            mkdir /tmp/test-results
            bundle exec rspec --format progress \
                              --out /tmp/test-results/rspec.xml \
                              $(circleci tests glob "spec/**/*_spec.rb" | circleci tests split --split-by=timings)
jobs:
  linters:
    executor: default
    steps:
      - defaults
      - run_linters
  run_specs:
    executor: default
    steps:
      - defaults
      - run_specs

workflows:
  version: 2
  build:
    jobs:
      - linters
      - run_specs:
          requires:
            - linters