version: 2.1

executors:
  default:
    working_directory: ~/repo
    docker:
      - image: cimg/ruby:3.1.2
        environment:
          BUNDLER_VERSION: 2.0.1
          parallelism: 3

commands:
  defaults:
    steps:
      - checkout
      - run: bundle install
  run_specs:
    steps:
      - run:
          name: run specs
          command: |
            mkdir /tmp/test-results
            bundle exec rspec --format progress \
                              --out /tmp/test-results/rspec.xml \
                              $(circleci tests glob "spec/**/*_spec.rb" | circleci tests split --split-by=timings)
      - store_test_results:
          path: test-results
  run_linters:
    steps:
      - run:
          name: rubocop
          command: rubocop
      - run:
          name: fasterer
          command: fasterer

jobs:
  linters:
    executor: default
    steps:
      - defaults
      - run_linters
  run_specs:
    executor: default
    steps:
      - defaults
      - run_specs

workflows:
  build:
    jobs:
      - linters
      - run_specs:
          requires:
            - linters

