version: 2.1

executors:
  default:
    working_directory: ~/repo
    docker:
      - image: cimg/ruby:3.1.2
commands:
  run_linters:
    steps:
      - run:
          name: rubocop
          command: bundle exec rubocop
      - run:
          name: fasterer
          command: fasterer
  run_specs:
    steps:
      - run:
          name: run specs
          command: |
            mkdir /tmp/test-results
            bundle exec rspec --format progress \
                              --out /tmp/test-results/rspec.xml \
                              $(circleci tests glob "spec/**/*_spec.rb" | circleci tests split --split-by=timings)
  setup_environment:
    steps:
      - checkout
      - run: bundle install --path vendor/bundle
jobs:
  linters:
    executor: default
    steps:
      - setup_environment
      - run_linters
  run_specs:
    executor: default
    steps:
      - setup_environment
      - run_specs

workflows:
  build:
    jobs:
      - linters
      - run_specs:
          requires:
            - linters